// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The authentication definition for blob storage destination. </summary>
    public partial class BlobStorageV1DestinationAuth
    {
        /// <summary> Initializes a new instance of BlobStorageV1DestinationAuth. </summary>
        public BlobStorageV1DestinationAuth()
        {
        }

        /// <summary> Initializes a new instance of BlobStorageV1DestinationAuth. </summary>
        /// <param name="type"> The kind of authentication to use. </param>
        internal BlobStorageV1DestinationAuth(string type)
        {
            Type = type;
        }

        /// <summary> The kind of authentication to use. </summary>
        internal string Type { get; set; }
    }
}
