// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The authentication definition with system assigned managed identity for azure data explorer destination. </summary>
    public partial class DataExplorerV1DestinationSystemAssignedManagedIdentityAuth : DataExplorerV1DestinationAuth
    {
        /// <summary> Initializes a new instance of DataExplorerV1DestinationSystemAssignedManagedIdentityAuth. </summary>
        public DataExplorerV1DestinationSystemAssignedManagedIdentityAuth()
        {
            Type = "systemAssignedManagedIdentity";
        }

        /// <summary> Initializes a new instance of DataExplorerV1DestinationSystemAssignedManagedIdentityAuth. </summary>
        /// <param name="type"> The kind of authentication to use. </param>
        internal DataExplorerV1DestinationSystemAssignedManagedIdentityAuth(string type) : base(type)
        {
            Type = type ?? "systemAssignedManagedIdentity";
        }
    }
}
