// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    public partial class DataExportStatus : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WriteEndObject();
        }

        internal static DataExportStatus DeserializeDataExportStatus(JsonElement element)
        {
            Optional<string> status = default;
            Optional<IReadOnlyList<DataExportError>> errors = default;
            Optional<DateTimeOffset> lastExportTime = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("status"))
                {
                    status = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("errors"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<DataExportError> array = new List<DataExportError>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DataExportError.DeserializeDataExportError(item));
                    }
                    errors = array;
                    continue;
                }
                if (property.NameEquals("lastExportTime"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    lastExportTime = property.Value.GetDateTimeOffset("O");
                    continue;
                }
            }
            return new DataExportStatus(status.Value, Optional.ToList(errors), Optional.ToNullable(lastExportTime));
        }
    }
}
