// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The edge device manifest migration job definition. </summary>
    public partial class DeviceManifestMigrationJobData : JobData
    {
        /// <summary> Initializes a new instance of DeviceManifestMigrationJobData. </summary>
        /// <param name="manifest"> The target manifest identifier to which devices will be migrated. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="manifest"/> is null. </exception>
        public DeviceManifestMigrationJobData(string manifest)
        {
            Argument.AssertNotNull(manifest, nameof(manifest));

            Manifest = manifest;
            Type = "deviceManifestMigration";
        }

        /// <summary> Initializes a new instance of DeviceManifestMigrationJobData. </summary>
        /// <param name="type"> Type of the job data. </param>
        /// <param name="manifest"> The target manifest identifier to which devices will be migrated. </param>
        internal DeviceManifestMigrationJobData(string type, string manifest) : base(type)
        {
            Manifest = manifest;
            Type = type ?? "deviceManifestMigration";
        }

        /// <summary> The target manifest identifier to which devices will be migrated. </summary>
        public string Manifest { get; set; }
    }
}
