// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The DeviceType. </summary>
    public readonly partial struct DeviceType : IEquatable<DeviceType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="DeviceType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DeviceType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string IotEdgeValue = "iotEdge";

        /// <summary> The edge device type. </summary>
        public static DeviceType IotEdge { get; } = new DeviceType(IotEdgeValue);
        /// <summary> Determines if two <see cref="DeviceType"/> values are the same. </summary>
        public static bool operator ==(DeviceType left, DeviceType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="DeviceType"/> values are not the same. </summary>
        public static bool operator !=(DeviceType left, DeviceType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="DeviceType"/>. </summary>
        public static implicit operator DeviceType(string value) => new DeviceType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is DeviceType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(DeviceType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
