// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The export destination definition. </summary>
    public partial class ExportDestination : Destination
    {
        /// <summary> Initializes a new instance of ExportDestination. </summary>
        /// <param name="displayName"> Display name of the destination. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="displayName"/> is null. </exception>
        public ExportDestination(string displayName) : base(displayName)
        {
            Argument.AssertNotNull(displayName, nameof(displayName));

            Type = "ExportDestination";
        }

        /// <summary> Initializes a new instance of ExportDestination. </summary>
        /// <param name="status"> Indication of the current health and operation of the export or destination. </param>
        /// <param name="errors"> Errors encountered by the export or destination. </param>
        /// <param name="lastExportTime"> The timestamp of the last message that was sent to the export or destination. </param>
        /// <param name="id"> Unique ID of the destination. </param>
        /// <param name="displayName"> Display name of the destination. </param>
        /// <param name="type"> The type of destination configuration. </param>
        /// <param name="transform"> Query for transforming the message structure to a particular output. </param>
        internal ExportDestination(string status, IReadOnlyList<DataExportError> errors, DateTimeOffset? lastExportTime, string id, string displayName, string type, string transform) : base(status, errors, lastExportTime, id, displayName, type)
        {
            Transform = transform;
            Type = type ?? "ExportDestination";
        }

        /// <summary> Query for transforming the message structure to a particular output. </summary>
        public string Transform { get; set; }
    }
}
