// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The state of the file upload configuration. </summary>
    public enum FileUploadState
    {
        /// <summary> pending. </summary>
        Pending,
        /// <summary> updating. </summary>
        Updating,
        /// <summary> deleting. </summary>
        Deleting,
        /// <summary> succeeded. </summary>
        Succeeded,
        /// <summary> failed. </summary>
        Failed
    }
}
