// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The attestation definition for an enrollment group. </summary>
    public partial class GroupAttestation
    {
        /// <summary> Initializes a new instance of GroupAttestation. </summary>
        public GroupAttestation()
        {
        }

        /// <summary> Initializes a new instance of GroupAttestation. </summary>
        /// <param name="type"> Type of the attestation. </param>
        internal GroupAttestation(string type)
        {
            Type = type;
        }

        /// <summary> Type of the attestation. </summary>
        internal string Type { get; set; }
    }
}
