// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    public partial class GroupTileConfiguration : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("group");
            writer.WriteStringValue(Group);
            writer.WritePropertyName("devices");
            writer.WriteStartArray();
            foreach (var item in Devices)
            {
                writer.WriteStringValue(item);
            }
            writer.WriteEndArray();
            writer.WriteEndObject();
        }

        internal static GroupTileConfiguration DeserializeGroupTileConfiguration(JsonElement element)
        {
            string group = default;
            IList<string> devices = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("group"))
                {
                    group = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("devices"))
                {
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    devices = array;
                    continue;
                }
            }
            return new GroupTileConfiguration(group, devices);
        }
    }
}
