// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    public partial class JobBatch : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type.ToSerialString());
            writer.WritePropertyName("value");
            writer.WriteNumberValue(Value);
            writer.WriteEndObject();
        }

        internal static JobBatch DeserializeJobBatch(JsonElement element)
        {
            JobBatchType type = default;
            float value = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString().ToJobBatchType();
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    value = property.Value.GetSingle();
                    continue;
                }
            }
            return new JobBatch(type, value);
        }
    }
}
