// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    internal partial class JobCollection
    {
        internal static JobCollection DeserializeJobCollection(JsonElement element)
        {
            IReadOnlyList<Job> value = default;
            Optional<string> nextLink = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("value"))
                {
                    List<Job> array = new List<Job>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(Job.DeserializeJob(item));
                    }
                    value = array;
                    continue;
                }
                if (property.NameEquals("nextLink"))
                {
                    nextLink = property.Value.GetString();
                    continue;
                }
            }
            return new JobCollection(value, nextLink.Value);
        }
    }
}
