// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The job data definition. </summary>
    public partial class JobData
    {
        /// <summary> Initializes a new instance of JobData. </summary>
        public JobData()
        {
        }

        /// <summary> Initializes a new instance of JobData. </summary>
        /// <param name="type"> Type of the job data. </param>
        internal JobData(string type)
        {
            Type = type;
        }

        /// <summary> Type of the job data. </summary>
        internal string Type { get; set; }
    }
}
