// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> Configuration specifying options for a last known value tile. </summary>
    public partial class LkvTileConfiguration : TileConfiguration
    {
        /// <summary> Initializes a new instance of LkvTileConfiguration. </summary>
        /// <param name="group"> The ID of the device group to display. </param>
        /// <param name="devices"> The list of associated devices to display. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="group"/> or <paramref name="devices"/> is null. </exception>
        public LkvTileConfiguration(string group, IEnumerable<string> devices)
        {
            Argument.AssertNotNull(group, nameof(group));
            Argument.AssertNotNull(devices, nameof(devices));

            Group = group;
            Devices = devices.ToList();
            Capabilities = new ChangeTrackingList<TileCapability>();
            Type = "lkv";
        }

        /// <summary> Initializes a new instance of LkvTileConfiguration. </summary>
        /// <param name="type"> The type of widget the tile renders. </param>
        /// <param name="showTrend"> Show the trend between the last known value and the value before that. </param>
        /// <param name="format"> The format configuration of the LKV tile. </param>
        /// <param name="group"> The ID of the device group to display. </param>
        /// <param name="devices"> The list of associated devices to display. </param>
        /// <param name="capabilities"></param>
        internal LkvTileConfiguration(string type, bool? showTrend, TextFormatConfiguration format, string group, IList<string> devices, IList<TileCapability> capabilities) : base(type)
        {
            ShowTrend = showTrend;
            Format = format;
            Group = group;
            Devices = devices;
            Capabilities = capabilities;
            Type = type ?? "lkv";
        }

        /// <summary> Show the trend between the last known value and the value before that. </summary>
        public bool? ShowTrend { get; set; }
        /// <summary> The format configuration of the LKV tile. </summary>
        public TextFormatConfiguration Format { get; set; }
        /// <summary> The ID of the device group to display. </summary>
        public string Group { get; set; }
        /// <summary> The list of associated devices to display. </summary>
        public IList<string> Devices { get; }
        /// <summary> Gets the capabilities. </summary>
        public IList<TileCapability> Capabilities { get; }
    }
}
