// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> Configuration specifying options for a map tile. </summary>
    public partial class MapTileConfiguration : GroupTileConfiguration
    {
        /// <summary> Initializes a new instance of MapTileConfiguration. </summary>
        /// <param name="group"> The ID of the device group to display. </param>
        /// <param name="devices"> The list of associated devices to display. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="group"/> or <paramref name="devices"/> is null. </exception>
        public MapTileConfiguration(string group, IEnumerable<string> devices) : base(group, devices)
        {
            Argument.AssertNotNull(group, nameof(group));
            Argument.AssertNotNull(devices, nameof(devices));

            Capabilities = new ChangeTrackingList<TileCapability>();
        }

        /// <summary> Initializes a new instance of MapTileConfiguration. </summary>
        /// <param name="group"> The ID of the device group to display. </param>
        /// <param name="devices"> The list of associated devices to display. </param>
        /// <param name="zoomLevel"> The zoom level of the map. </param>
        /// <param name="capabilities"></param>
        internal MapTileConfiguration(string group, IList<string> devices, float? zoomLevel, IList<TileCapability> capabilities) : base(group, devices)
        {
            ZoomLevel = zoomLevel;
            Capabilities = capabilities;
        }

        /// <summary> The zoom level of the map. </summary>
        public float? ZoomLevel { get; set; }
        /// <summary> Gets the capabilities. </summary>
        public IList<TileCapability> Capabilities { get; }
    }
}
