// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    internal static partial class OAuthRequestTypeExtensions
    {
        public static string ToSerialString(this OAuthRequestType value) => value switch
        {
            OAuthRequestType.Auto => "auto",
            OAuthRequestType.Json => "json",
            OAuthRequestType.UrlEncoded => "urlencoded",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OAuthRequestType value.")
        };

        public static OAuthRequestType ToOAuthRequestType(this string value)
        {
            if (string.Equals(value, "auto", StringComparison.InvariantCultureIgnoreCase)) return OAuthRequestType.Auto;
            if (string.Equals(value, "json", StringComparison.InvariantCultureIgnoreCase)) return OAuthRequestType.Json;
            if (string.Equals(value, "urlencoded", StringComparison.InvariantCultureIgnoreCase)) return OAuthRequestType.UrlEncoded;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OAuthRequestType value.");
        }
    }
}
