// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    public partial class PieChartConfiguration : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("queryRange");
            writer.WriteObjectValue(QueryRange);
            if (Optional.IsDefined(Format))
            {
                writer.WritePropertyName("format");
                writer.WriteObjectValue(Format);
            }
            writer.WritePropertyName("group");
            writer.WriteStringValue(Group);
            writer.WritePropertyName("devices");
            writer.WriteStartArray();
            foreach (var item in Devices)
            {
                writer.WriteStringValue(item);
            }
            writer.WriteEndArray();
            if (Optional.IsCollectionDefined(Capabilities))
            {
                writer.WritePropertyName("capabilities");
                writer.WriteStartArray();
                foreach (var item in Capabilities)
                {
                    writer.WriteObjectValue(item);
                }
                writer.WriteEndArray();
            }
            writer.WritePropertyName("type");
            writer.WriteStringValue(Type);
            writer.WriteEndObject();
        }

        internal static PieChartConfiguration DeserializePieChartConfiguration(JsonElement element)
        {
            TimeQueryRangeConfiguration queryRange = default;
            Optional<ChartFormatConfiguration> format = default;
            string group = default;
            IList<string> devices = default;
            Optional<IList<TileCapability>> capabilities = default;
            string type = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("queryRange"))
                {
                    queryRange = TimeQueryRangeConfiguration.DeserializeTimeQueryRangeConfiguration(property.Value);
                    continue;
                }
                if (property.NameEquals("format"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    format = ChartFormatConfiguration.DeserializeChartFormatConfiguration(property.Value);
                    continue;
                }
                if (property.NameEquals("group"))
                {
                    group = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("devices"))
                {
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    devices = array;
                    continue;
                }
                if (property.NameEquals("capabilities"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<TileCapability> array = new List<TileCapability>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(TileCapability.DeserializeTileCapability(item));
                    }
                    capabilities = array;
                    continue;
                }
                if (property.NameEquals("type"))
                {
                    type = property.Value.GetString();
                    continue;
                }
            }
            return new PieChartConfiguration(type, queryRange, format.Value, group, devices, Optional.ToList(capabilities));
        }
    }
}
