// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The authentication definition with system assigned managed identity for service bus topic destination. </summary>
    public partial class ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth : ServiceBusTopicV1DestinationAuth
    {
        /// <summary> Initializes a new instance of ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth. </summary>
        /// <param name="hostName"> The host name of the Service Bus namespace. </param>
        /// <param name="topicName"> The Service Bus topic name. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="hostName"/> or <paramref name="topicName"/> is null. </exception>
        public ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth(string hostName, string topicName)
        {
            Argument.AssertNotNull(hostName, nameof(hostName));
            Argument.AssertNotNull(topicName, nameof(topicName));

            HostName = hostName;
            TopicName = topicName;
            Type = "systemAssignedManagedIdentity";
        }

        /// <summary> Initializes a new instance of ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth. </summary>
        /// <param name="type"> The kind of authentication to use. </param>
        /// <param name="hostName"> The host name of the Service Bus namespace. </param>
        /// <param name="topicName"> The Service Bus topic name. </param>
        internal ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth(string type, string hostName, string topicName) : base(type)
        {
            HostName = hostName;
            TopicName = topicName;
            Type = type ?? "systemAssignedManagedIdentity";
        }

        /// <summary> The host name of the Service Bus namespace. </summary>
        public string HostName { get; set; }
        /// <summary> The Service Bus topic name. </summary>
        public string TopicName { get; set; }
    }
}
