// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The service principal user definition. </summary>
    public partial class ServicePrincipalUser : User
    {
        /// <summary> Initializes a new instance of ServicePrincipalUser. </summary>
        /// <param name="roles"> List of role assignments that specify the permissions to access the application. </param>
        /// <param name="tenantId"> The AAD tenant ID of the service principal. </param>
        /// <param name="objectId"> The AAD object ID of the service principal. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="roles"/>, <paramref name="tenantId"/> or <paramref name="objectId"/> is null. </exception>
        public ServicePrincipalUser(IEnumerable<RoleAssignment> roles, string tenantId, string objectId) : base(roles)
        {
            Argument.AssertNotNull(roles, nameof(roles));
            Argument.AssertNotNull(tenantId, nameof(tenantId));
            Argument.AssertNotNull(objectId, nameof(objectId));

            TenantId = tenantId;
            ObjectId = objectId;
            Type = "servicePrincipal";
        }

        /// <summary> Initializes a new instance of ServicePrincipalUser. </summary>
        /// <param name="roles"> List of role assignments that specify the permissions to access the application. </param>
        /// <param name="id"> Unique ID of the user. </param>
        /// <param name="type"> Type of the user. </param>
        /// <param name="tenantId"> The AAD tenant ID of the service principal. </param>
        /// <param name="objectId"> The AAD object ID of the service principal. </param>
        internal ServicePrincipalUser(IList<RoleAssignment> roles, string id, string type, string tenantId, string objectId) : base(roles, id, type)
        {
            TenantId = tenantId;
            ObjectId = objectId;
            Type = type ?? "servicePrincipal";
        }

        /// <summary> The AAD tenant ID of the service principal. </summary>
        public string TenantId { get; set; }
        /// <summary> The AAD object ID of the service principal. </summary>
        public string ObjectId { get; set; }
    }
}
