// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    public partial class SigningX509Certificates : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Primary))
            {
                writer.WritePropertyName("primary");
                writer.WriteObjectValue(Primary);
            }
            if (Optional.IsDefined(Secondary))
            {
                writer.WritePropertyName("secondary");
                writer.WriteObjectValue(Secondary);
            }
            writer.WriteEndObject();
        }

        internal static SigningX509Certificates DeserializeSigningX509Certificates(JsonElement element)
        {
            Optional<SigningX509Certificate> primary = default;
            Optional<SigningX509Certificate> secondary = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("primary"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    primary = SigningX509Certificate.DeserializeSigningX509Certificate(property.Value);
                    continue;
                }
                if (property.NameEquals("secondary"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    secondary = SigningX509Certificate.DeserializeSigningX509Certificate(property.Value);
                    continue;
                }
            }
            return new SigningX509Certificates(primary.Value, secondary.Value);
        }
    }
}
