// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Microsoft.Azure.IoTCentral.Preview.Models
{
    /// <summary> The webhook destination definition. </summary>
    public partial class WebhookV1Destination : Destination
    {
        /// <summary> Initializes a new instance of WebhookV1Destination. </summary>
        /// <param name="displayName"> Display name of the destination. </param>
        /// <param name="url"> The URL to invoke when exporting data. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="displayName"/> or <paramref name="url"/> is null. </exception>
        public WebhookV1Destination(string displayName, string url) : base(displayName)
        {
            Argument.AssertNotNull(displayName, nameof(displayName));
            Argument.AssertNotNull(url, nameof(url));

            Url = url;
            QueryCustomizations = new ChangeTrackingDictionary<string, WebhookV1DestinationCustomization>();
            HeaderCustomizations = new ChangeTrackingDictionary<string, WebhookV1DestinationCustomization>();
            Type = "webhook@v1";
        }

        /// <summary> Initializes a new instance of WebhookV1Destination. </summary>
        /// <param name="status"> Indication of the current health and operation of the export or destination. </param>
        /// <param name="errors"> Errors encountered by the export or destination. </param>
        /// <param name="lastExportTime"> The timestamp of the last message that was sent to the export or destination. </param>
        /// <param name="id"> Unique ID of the destination. </param>
        /// <param name="displayName"> Display name of the destination. </param>
        /// <param name="type"> The type of destination configuration. </param>
        /// <param name="url"> The URL to invoke when exporting data. </param>
        /// <param name="queryCustomizations"> Additional query parameters that should be added to each request. </param>
        /// <param name="headerCustomizations"> Additional headers that should be added to each request. </param>
        /// <param name="authorization"> The authentication definition for webhook destination. </param>
        internal WebhookV1Destination(string status, IReadOnlyList<DataExportError> errors, DateTimeOffset? lastExportTime, string id, string displayName, string type, string url, IDictionary<string, WebhookV1DestinationCustomization> queryCustomizations, IDictionary<string, WebhookV1DestinationCustomization> headerCustomizations, WebhookV1DestinationAuth authorization) : base(status, errors, lastExportTime, id, displayName, type)
        {
            Url = url;
            QueryCustomizations = queryCustomizations;
            HeaderCustomizations = headerCustomizations;
            Authorization = authorization;
            Type = type ?? "webhook@v1";
        }

        /// <summary> The URL to invoke when exporting data. </summary>
        public string Url { get; set; }
        /// <summary> Additional query parameters that should be added to each request. </summary>
        public IDictionary<string, WebhookV1DestinationCustomization> QueryCustomizations { get; }
        /// <summary> Additional headers that should be added to each request. </summary>
        public IDictionary<string, WebhookV1DestinationCustomization> HeaderCustomizations { get; }
        /// <summary> The authentication definition for webhook destination. </summary>
        public WebhookV1DestinationAuth Authorization { get; set; }
    }
}
