// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.Azure.IoTCentral.Preview.Models;

namespace Microsoft.Azure.IoTCentral.Preview
{
    /// <summary> The Dashboards service client. </summary>
    public partial class DashboardsClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal DashboardsRestClient RestClient { get; }

        /// <summary> Initializes a new instance of DashboardsClient for mocking. </summary>
        protected DashboardsClient()
        {
        }

        /// <summary> Initializes a new instance of DashboardsClient. </summary>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="credential"> A credential used to authenticate to an Azure Service. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public DashboardsClient(string subdomain, TokenCredential credential, string baseDomain = "azureiotcentral.com", AzureIoTCentralClientOptions options = null)
        {
            if (subdomain == null)
            {
                throw new ArgumentNullException(nameof(subdomain));
            }
            if (credential == null)
            {
                throw new ArgumentNullException(nameof(credential));
            }
            if (baseDomain == null)
            {
                throw new ArgumentNullException(nameof(baseDomain));
            }

            options ??= new AzureIoTCentralClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            string[] scopes = { "https://apps.azureiotcentral.com/.default" };
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, scopes));
            RestClient = new DashboardsRestClient(_clientDiagnostics, _pipeline, subdomain, baseDomain, options.Version);
        }

        /// <summary> Initializes a new instance of DashboardsClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="apiVersion"> Api Version. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/>, <paramref name="pipeline"/>, <paramref name="subdomain"/>, <paramref name="baseDomain"/> or <paramref name="apiVersion"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="subdomain"/> is an empty string, and was expected to be non-empty. </exception>
        internal DashboardsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string subdomain, string baseDomain = "azureiotcentral.com", string apiVersion = "2022-10-31-preview")
        {
            RestClient = new DashboardsRestClient(clientDiagnostics, pipeline, subdomain, baseDomain, apiVersion);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Get a dashboard by ID. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Dashboard>> GetAsync(string dashboardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Get");
            scope.Start();
            try
            {
                return await RestClient.GetAsync(dashboardId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get a dashboard by ID. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Dashboard> Get(string dashboardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Get");
            scope.Start();
            try
            {
                return RestClient.Get(dashboardId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="body"> Dashboard definition. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Dashboard>> CreateAsync(string dashboardId, Dashboard body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(dashboardId, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="body"> Dashboard definition. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Dashboard> Create(string dashboardId, Dashboard body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(dashboardId, body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="body"> Dashboard definition. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Dashboard>> UpdateAsync(string dashboardId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Update");
            scope.Start();
            try
            {
                return await RestClient.UpdateAsync(dashboardId, body, ifMatch, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="body"> Dashboard definition. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Dashboard> Update(string dashboardId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Update");
            scope.Start();
            try
            {
                return RestClient.Update(dashboardId, body, ifMatch, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response> RemoveAsync(string dashboardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Remove");
            scope.Start();
            try
            {
                return await RestClient.RemoveAsync(dashboardId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a dashboard. </summary>
        /// <param name="dashboardId"> Unique ID for the dashboard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response Remove(string dashboardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DashboardsClient.Remove");
            scope.Start();
            try
            {
                return RestClient.Remove(dashboardId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get the list of dashboards in an application. </summary>
        /// <param name="filter"> An expression on the resource type that selects the resources to be returned. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="orderby"> An expression that specify the order of the returned resources. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual AsyncPageable<Dashboard> ListAsync(string filter = null, int? maxpagesize = null, string orderby = null, CancellationToken cancellationToken = default)
        {
            async Task<Page<Dashboard>> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DashboardsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListAsync(filter, maxpagesize, orderby, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            async Task<Page<Dashboard>> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DashboardsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListNextPageAsync(nextLink, filter, maxpagesize, orderby, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the list of dashboards in an application. </summary>
        /// <param name="filter"> An expression on the resource type that selects the resources to be returned. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="orderby"> An expression that specify the order of the returned resources. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Pageable<Dashboard> List(string filter = null, int? maxpagesize = null, string orderby = null, CancellationToken cancellationToken = default)
        {
            Page<Dashboard> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DashboardsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.List(filter, maxpagesize, orderby, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            Page<Dashboard> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DashboardsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.ListNextPage(nextLink, filter, maxpagesize, orderby, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateEnumerable(FirstPageFunc, NextPageFunc);
        }
    }
}
