// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.Azure.IoTCentral.Preview.Models;

namespace Microsoft.Azure.IoTCentral.Preview
{
    /// <summary> The DeviceGroups service client. </summary>
    public partial class DeviceGroupsClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal DeviceGroupsRestClient RestClient { get; }

        /// <summary> Initializes a new instance of DeviceGroupsClient for mocking. </summary>
        protected DeviceGroupsClient()
        {
        }

        /// <summary> Initializes a new instance of DeviceGroupsClient. </summary>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="credential"> A credential used to authenticate to an Azure Service. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public DeviceGroupsClient(string subdomain, TokenCredential credential, string baseDomain = "azureiotcentral.com", AzureIoTCentralClientOptions options = null)
        {
            if (subdomain == null)
            {
                throw new ArgumentNullException(nameof(subdomain));
            }
            if (credential == null)
            {
                throw new ArgumentNullException(nameof(credential));
            }
            if (baseDomain == null)
            {
                throw new ArgumentNullException(nameof(baseDomain));
            }

            options ??= new AzureIoTCentralClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            string[] scopes = { "https://apps.azureiotcentral.com/.default" };
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, scopes));
            RestClient = new DeviceGroupsRestClient(_clientDiagnostics, _pipeline, subdomain, baseDomain, options.Version);
        }

        /// <summary> Initializes a new instance of DeviceGroupsClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="apiVersion"> Api Version. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/>, <paramref name="pipeline"/>, <paramref name="subdomain"/>, <paramref name="baseDomain"/> or <paramref name="apiVersion"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="subdomain"/> is an empty string, and was expected to be non-empty. </exception>
        internal DeviceGroupsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string subdomain, string baseDomain = "azureiotcentral.com", string apiVersion = "2022-10-31-preview")
        {
            RestClient = new DeviceGroupsRestClient(clientDiagnostics, pipeline, subdomain, baseDomain, apiVersion);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Get the device group by ID. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<DeviceGroup>> GetAsync(string deviceGroupId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Get");
            scope.Start();
            try
            {
                return await RestClient.GetAsync(deviceGroupId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get the device group by ID. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<DeviceGroup> Get(string deviceGroupId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Get");
            scope.Start();
            try
            {
                return RestClient.Get(deviceGroupId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create or update a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="body"> Device group body. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Create or update a device group. </remarks>
        public virtual async Task<Response<DeviceGroup>> CreateAsync(string deviceGroupId, DeviceGroup body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(deviceGroupId, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create or update a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="body"> Device group body. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Create or update a device group. </remarks>
        public virtual Response<DeviceGroup> Create(string deviceGroupId, DeviceGroup body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(deviceGroupId, body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a device group via patch. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="body"> Device group patch body. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Update an existing device group by ID. </remarks>
        public virtual async Task<Response<DeviceGroup>> UpdateAsync(string deviceGroupId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Update");
            scope.Start();
            try
            {
                return await RestClient.UpdateAsync(deviceGroupId, body, ifMatch, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a device group via patch. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="body"> Device group patch body. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Update an existing device group by ID. </remarks>
        public virtual Response<DeviceGroup> Update(string deviceGroupId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Update");
            scope.Start();
            try
            {
                return RestClient.Update(deviceGroupId, body, ifMatch, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response> RemoveAsync(string deviceGroupId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Remove");
            scope.Start();
            try
            {
                return await RestClient.RemoveAsync(deviceGroupId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response Remove(string deviceGroupId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.Remove");
            scope.Start();
            try
            {
                return RestClient.Remove(deviceGroupId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get the list of device groups in an application. </summary>
        /// <param name="filter"> An expression on the resource type that selects the resources to be returned. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="orderby"> An expression that specify the order of the returned resources. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual AsyncPageable<DeviceGroup> ListAsync(string filter = null, int? maxpagesize = null, string orderby = null, CancellationToken cancellationToken = default)
        {
            async Task<Page<DeviceGroup>> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListAsync(filter, maxpagesize, orderby, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            async Task<Page<DeviceGroup>> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListNextPageAsync(nextLink, filter, maxpagesize, orderby, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the list of device groups in an application. </summary>
        /// <param name="filter"> An expression on the resource type that selects the resources to be returned. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="orderby"> An expression that specify the order of the returned resources. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Pageable<DeviceGroup> List(string filter = null, int? maxpagesize = null, string orderby = null, CancellationToken cancellationToken = default)
        {
            Page<DeviceGroup> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.List(filter, maxpagesize, orderby, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            Page<DeviceGroup> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.ListNextPage(nextLink, filter, maxpagesize, orderby, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the devices of a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="deviceGroupId"/> is null. </exception>
        /// <remarks> Get the list of devices by device group ID. </remarks>
        public virtual AsyncPageable<Device> GetDevicesAsync(string deviceGroupId, int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            if (deviceGroupId == null)
            {
                throw new ArgumentNullException(nameof(deviceGroupId));
            }

            async Task<Page<Device>> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.GetDevices");
                scope.Start();
                try
                {
                    var response = await RestClient.GetDevicesAsync(deviceGroupId, maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            async Task<Page<Device>> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.GetDevices");
                scope.Start();
                try
                {
                    var response = await RestClient.GetDevicesNextPageAsync(nextLink, deviceGroupId, maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the devices of a device group. </summary>
        /// <param name="deviceGroupId"> Unique ID for the device group. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="deviceGroupId"/> is null. </exception>
        /// <remarks> Get the list of devices by device group ID. </remarks>
        public virtual Pageable<Device> GetDevices(string deviceGroupId, int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            if (deviceGroupId == null)
            {
                throw new ArgumentNullException(nameof(deviceGroupId));
            }

            Page<Device> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.GetDevices");
                scope.Start();
                try
                {
                    var response = RestClient.GetDevices(deviceGroupId, maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            Page<Device> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("DeviceGroupsClient.GetDevices");
                scope.Start();
                try
                {
                    var response = RestClient.GetDevicesNextPage(nextLink, deviceGroupId, maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateEnumerable(FirstPageFunc, NextPageFunc);
        }
    }
}
