// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.Azure.IoTCentral.Preview.Models;

namespace Microsoft.Azure.IoTCentral.Preview
{
    /// <summary> The ScheduledJobs service client. </summary>
    public partial class ScheduledJobsClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal ScheduledJobsRestClient RestClient { get; }

        /// <summary> Initializes a new instance of ScheduledJobsClient for mocking. </summary>
        protected ScheduledJobsClient()
        {
        }

        /// <summary> Initializes a new instance of ScheduledJobsClient. </summary>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="credential"> A credential used to authenticate to an Azure Service. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public ScheduledJobsClient(string subdomain, TokenCredential credential, string baseDomain = "azureiotcentral.com", AzureIoTCentralClientOptions options = null)
        {
            if (subdomain == null)
            {
                throw new ArgumentNullException(nameof(subdomain));
            }
            if (credential == null)
            {
                throw new ArgumentNullException(nameof(credential));
            }
            if (baseDomain == null)
            {
                throw new ArgumentNullException(nameof(baseDomain));
            }

            options ??= new AzureIoTCentralClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            string[] scopes = { "https://apps.azureiotcentral.com/.default" };
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, scopes));
            RestClient = new ScheduledJobsRestClient(_clientDiagnostics, _pipeline, subdomain, baseDomain, options.Version);
        }

        /// <summary> Initializes a new instance of ScheduledJobsClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="subdomain"> The application subdomain. </param>
        /// <param name="baseDomain"> The base domain for all Azure IoT Central service requests. </param>
        /// <param name="apiVersion"> Api Version. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/>, <paramref name="pipeline"/>, <paramref name="subdomain"/>, <paramref name="baseDomain"/> or <paramref name="apiVersion"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="subdomain"/> is an empty string, and was expected to be non-empty. </exception>
        internal ScheduledJobsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string subdomain, string baseDomain = "azureiotcentral.com", string apiVersion = "2022-10-31-preview")
        {
            RestClient = new ScheduledJobsRestClient(clientDiagnostics, pipeline, subdomain, baseDomain, apiVersion);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Get a scheduled job by ID. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Get details about a scheduled job by ID. </remarks>
        public virtual async Task<Response<ScheduledJob>> GetAsync(string scheduledJobId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Get");
            scope.Start();
            try
            {
                return await RestClient.GetAsync(scheduledJobId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get a scheduled job by ID. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Get details about a scheduled job by ID. </remarks>
        public virtual Response<ScheduledJob> Get(string scheduledJobId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Get");
            scope.Start();
            try
            {
                return RestClient.Get(scheduledJobId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create or update a scheduled job. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="body"> Scheduled job definition. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Create or update a scheduled job by ID. </remarks>
        public virtual async Task<Response<ScheduledJob>> CreateAsync(string scheduledJobId, ScheduledJob body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(scheduledJobId, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create or update a scheduled job. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="body"> Scheduled job definition. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Create or update a scheduled job by ID. </remarks>
        public virtual Response<ScheduledJob> Create(string scheduledJobId, ScheduledJob body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(scheduledJobId, body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a scheduled job via patch. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="body"> Scheduled job patch. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Update an existing scheduled job by ID. </remarks>
        public virtual async Task<Response<ScheduledJob>> UpdateAsync(string scheduledJobId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Update");
            scope.Start();
            try
            {
                return await RestClient.UpdateAsync(scheduledJobId, body, ifMatch, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Update a scheduled job via patch. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="body"> Scheduled job patch. </param>
        /// <param name="ifMatch"> Only perform the operation if the entity&apos;s etag matches one of the etags provided or * is provided. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Update an existing scheduled job by ID. </remarks>
        public virtual Response<ScheduledJob> Update(string scheduledJobId, object body, string ifMatch = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Update");
            scope.Start();
            try
            {
                return RestClient.Update(scheduledJobId, body, ifMatch, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a scheduled job. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Delete an existing scheduled job by ID. </remarks>
        public virtual async Task<Response> RemoveAsync(string scheduledJobId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Remove");
            scope.Start();
            try
            {
                return await RestClient.RemoveAsync(scheduledJobId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Delete a scheduled job. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Delete an existing scheduled job by ID. </remarks>
        public virtual Response Remove(string scheduledJobId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.Remove");
            scope.Start();
            try
            {
                return RestClient.Remove(scheduledJobId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Get the list of scheduled job definitions in an application. </summary>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual AsyncPageable<ScheduledJob> ListAsync(int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            async Task<Page<ScheduledJob>> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListAsync(maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            async Task<Page<ScheduledJob>> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.List");
                scope.Start();
                try
                {
                    var response = await RestClient.ListNextPageAsync(nextLink, maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the list of scheduled job definitions in an application. </summary>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Pageable<ScheduledJob> List(int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            Page<ScheduledJob> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.List(maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            Page<ScheduledJob> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.List");
                scope.Start();
                try
                {
                    var response = RestClient.ListNextPage(nextLink, maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the list of jobs for a scheduled job definition. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="scheduledJobId"/> is null. </exception>
        public virtual AsyncPageable<Job> ListJobsAsync(string scheduledJobId, int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            if (scheduledJobId == null)
            {
                throw new ArgumentNullException(nameof(scheduledJobId));
            }

            async Task<Page<Job>> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.ListJobs");
                scope.Start();
                try
                {
                    var response = await RestClient.ListJobsAsync(scheduledJobId, maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            async Task<Page<Job>> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.ListJobs");
                scope.Start();
                try
                {
                    var response = await RestClient.ListJobsNextPageAsync(nextLink, scheduledJobId, maxpagesize, cancellationToken).ConfigureAwait(false);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateAsyncEnumerable(FirstPageFunc, NextPageFunc);
        }

        /// <summary> Get the list of jobs for a scheduled job definition. </summary>
        /// <param name="scheduledJobId"> Unique ID of the scheduled job. </param>
        /// <param name="maxpagesize"> The maximum number of resources to return from one response. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="scheduledJobId"/> is null. </exception>
        public virtual Pageable<Job> ListJobs(string scheduledJobId, int? maxpagesize = null, CancellationToken cancellationToken = default)
        {
            if (scheduledJobId == null)
            {
                throw new ArgumentNullException(nameof(scheduledJobId));
            }

            Page<Job> FirstPageFunc(int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.ListJobs");
                scope.Start();
                try
                {
                    var response = RestClient.ListJobs(scheduledJobId, maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            Page<Job> NextPageFunc(string nextLink, int? pageSizeHint)
            {
                using var scope = _clientDiagnostics.CreateScope("ScheduledJobsClient.ListJobs");
                scope.Start();
                try
                {
                    var response = RestClient.ListJobsNextPage(nextLink, scheduledJobId, maxpagesize, cancellationToken);
                    return Page.FromValues(response.Value.Value, response.Value.NextLink, response.GetRawResponse());
                }
                catch (Exception e)
                {
                    scope.Failed(e);
                    throw;
                }
            }
            return PageableHelpers.CreateEnumerable(FirstPageFunc, NextPageFunc);
        }
    }
}
