// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The active directory group user definition.
    /// </summary>
    [Newtonsoft.Json.JsonObject("adGroup")]
    public partial class ADGroupUser : User
    {
        /// <summary>
        /// Initializes a new instance of the ADGroupUser class.
        /// </summary>
        public ADGroupUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ADGroupUser class.
        /// </summary>
        /// <param name="roles">List of role assignments that specify the
        /// permissions to access the application.</param>
        /// <param name="tenantId">The AAD tenant ID of the AD Group.</param>
        /// <param name="objectId">The AAD object ID of the AD Group.</param>
        /// <param name="id">Unique ID of the user.</param>
        public ADGroupUser(IList<RoleAssignment> roles, string tenantId, string objectId, string id = default(string))
            : base(roles, id)
        {
            TenantId = tenantId;
            ObjectId = objectId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the AAD tenant ID of the AD Group.
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or sets the AAD object ID of the AD Group.
        /// </summary>
        [JsonProperty(PropertyName = "objectId")]
        public string ObjectId { get; set; }

    }
}
