// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The device credentials definition.
    /// </summary>
    public partial class DeviceCredentials
    {
        /// <summary>
        /// Initializes a new instance of the DeviceCredentials class.
        /// </summary>
        public DeviceCredentials()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeviceCredentials class.
        /// </summary>
        /// <param name="idScope">ID scope for connecting to the IoT Central
        /// application.</param>
        /// <param name="symmetricKey">The symmetric key credentials for the
        /// device.</param>
        /// <param name="x509">The X.509 credential information for the
        /// device.</param>
        /// <param name="tpm">The TPM credentials for the device.</param>
        public DeviceCredentials(string idScope, SymmetricKey symmetricKey = default(SymmetricKey), X509 x509 = default(X509), Tpm tpm = default(Tpm))
        {
            IdScope = idScope;
            SymmetricKey = symmetricKey;
            X509 = x509;
            Tpm = tpm;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets ID scope for connecting to the IoT Central
        /// application.
        /// </summary>
        [JsonProperty(PropertyName = "idScope")]
        public string IdScope { get; set; }

        /// <summary>
        /// Gets or sets the symmetric key credentials for the device.
        /// </summary>
        [JsonProperty(PropertyName = "symmetricKey")]
        public SymmetricKey SymmetricKey { get; set; }

        /// <summary>
        /// Gets or sets the X.509 credential information for the device.
        /// </summary>
        [JsonProperty(PropertyName = "x509")]
        public X509 X509 { get; set; }

        /// <summary>
        /// Gets or sets the TPM credentials for the device.
        /// </summary>
        [JsonProperty(PropertyName = "tpm")]
        public Tpm Tpm { get; set; }

    }
}
