// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for JobBatchType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobBatchType
    {
        /// <summary>
        /// Job Batching based on number of devices.
        /// </summary>
        [EnumMember(Value = "number")]
        Number,
        /// <summary>
        /// Job Batching based percentage of total applied devices.
        /// </summary>
        [EnumMember(Value = "percentage")]
        Percentage
    }
    internal static class JobBatchTypeEnumExtension
    {
        internal static string ToSerializedValue(this JobBatchType? value)
        {
            return value == null ? null : ((JobBatchType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this JobBatchType value)
        {
            switch( value )
            {
                case JobBatchType.Number:
                    return "number";
                case JobBatchType.Percentage:
                    return "percentage";
            }
            return null;
        }

        internal static JobBatchType? ParseJobBatchType(this string value)
        {
            switch( value )
            {
                case "number":
                    return JobBatchType.Number;
                case "percentage":
                    return JobBatchType.Percentage;
            }
            return null;
        }
    }
}
