// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The job device status definition.
    /// </summary>
    public partial class JobDeviceStatus
    {
        /// <summary>
        /// Initializes a new instance of the JobDeviceStatus class.
        /// </summary>
        public JobDeviceStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobDeviceStatus class.
        /// </summary>
        /// <param name="id">ID of the device whose job status is being
        /// provided.</param>
        /// <param name="status">Indicates whether the job is starting,
        /// running, etc. for the given device.</param>
        public JobDeviceStatus(string id = default(string), string status = default(string))
        {
            Id = id;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets ID of the device whose job status is being provided.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; private set; }

        /// <summary>
        /// Gets indicates whether the job is starting, running, etc. for the
        /// given device.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; private set; }

    }
}
