// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The X509 attestation definition.
    /// </summary>
    [Newtonsoft.Json.JsonObject("x509")]
    public partial class X509Attestation : Attestation
    {
        /// <summary>
        /// Initializes a new instance of the X509Attestation class.
        /// </summary>
        public X509Attestation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the X509Attestation class.
        /// </summary>
        /// <param name="x509">The X.509 credentials for this
        /// attestation.</param>
        public X509Attestation(X509 x509)
        {
            X509 = x509;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the X.509 credentials for this attestation.
        /// </summary>
        [JsonProperty(PropertyName = "x509")]
        public X509 X509 { get; set; }

    }
}
