// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The X509 definition.
    /// </summary>
    public partial class X509
    {
        /// <summary>
        /// Initializes a new instance of the X509 class.
        /// </summary>
        public X509()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the X509 class.
        /// </summary>
        /// <param name="clientCertificates">The X.509 client certificates for
        /// this credential.</param>
        public X509(X509Certificates clientCertificates = default(X509Certificates))
        {
            ClientCertificates = clientCertificates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the X.509 client certificates for this credential.
        /// </summary>
        [JsonProperty(PropertyName = "clientCertificates")]
        public X509Certificates ClientCertificates { get; set; }

    }
}
