// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.IoTCentral
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// Azure IoT Central is a service that makes it easy to connect, monitor,
    /// and manage your IoT devices at scale.
    /// </summary>
    public partial interface IAzureIoTCentral : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// The base domain for all Azure IoT Central service requests.
        /// </summary>
        string BaseDomain { get; set; }

        /// <summary>
        /// The application subdomain.
        /// </summary>
        string Subdomain { get; set; }

        /// <summary>
        /// The version of the API being called.
        /// </summary>
        string ApiVersion { get; set; }


        /// <summary>
        /// Gets the IApiTokens.
        /// </summary>
        IApiTokens ApiTokens { get; }

        /// <summary>
        /// Gets the IDeviceGroups.
        /// </summary>
        IDeviceGroups DeviceGroups { get; }

        /// <summary>
        /// Gets the IDeviceTemplates.
        /// </summary>
        IDeviceTemplates DeviceTemplates { get; }

        /// <summary>
        /// Gets the IDevices.
        /// </summary>
        IDevices Devices { get; }

        /// <summary>
        /// Gets the IEnrollmentGroups.
        /// </summary>
        IEnrollmentGroups EnrollmentGroups { get; }

        /// <summary>
        /// Gets the IFileUploads.
        /// </summary>
        IFileUploads FileUploads { get; }

        /// <summary>
        /// Gets the IJobs.
        /// </summary>
        IJobs Jobs { get; }

        /// <summary>
        /// Gets the IOrganizations.
        /// </summary>
        IOrganizations Organizations { get; }

        /// <summary>
        /// Gets the IRoles.
        /// </summary>
        IRoles Roles { get; }

        /// <summary>
        /// Gets the IScheduledJobs.
        /// </summary>
        IScheduledJobs ScheduledJobs { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

    }
}
